Update source to fix fontmake bracket layer error
Fontmake gives an error when running the build script:
    ValueError: Currently, we only support bracket layers that
    are present on all masters, i.e. what the Glyphs.app
    tutorial calls 'Changing All Masters'. There is a/are bracket
    layer(s) missing for glyph(s) ['Oslash', 'oslash', 'dollar'].

This commit Adds bracket layers for the regular weight masters of
'Oslash', 'oslash', and 'dollar'.